//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdoNet.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subject
    {
        public int SubjectId { get; set; }
        public string Name { get; set; }
        public Nullable<int> Student_StudentId { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
